export type OrganizationRole = "owner" | "admin" | "member";
export type BusinessStatus = "draft" | "researching" | "building" | "ready" | "published" | "paused";
export type BusinessType = "dropshipping";
export type AiJobStatus = "queued" | "running" | "completed" | "failed" | "cancelled";
export interface Profile { id:string; email:string; full_name:string|null; avatar_url:string|null; created_at:string; updated_at:string }
export interface Organization { id:string; name:string; slug:string; owner_id:string; created_at:string; updated_at:string }
export interface Business { id:string; organization_id:string; name:string; slug:string; status:BusinessStatus; business_type:BusinessType; target_country:string; target_market:string; starting_budget:number; niche:string; created_at:string; updated_at:string }
export type ProductResearchStatus = "queued" | "running" | "completed" | "failed";
export type ProductOpportunityStatus = "discovered" | "shortlisted" | "selected" | "rejected";
export interface ProductResearchRun { id:string; organization_id:string; business_id:string; status:ProductResearchStatus; target_market:string; target_country:string; niche:string; budget:number; maximum_supplier_cost:number; preferred_selling_price:number; requested_product_count:number; created_at:string; started_at:string|null; completed_at:string|null; error:string|null }
export interface ProductOpportunity { id:string; organization_id:string; business_id:string; research_run_id:string; name:string; category:string; description:string; target_customer:string; supplier_cost:number; suggested_price:number; estimated_margin:number; currency:string; demand_score:number; competition_score:number; trend_score:number; marketing_score:number; shipping_score:number; risk_score:number; margin_score:number; overall_score:number; reasoning:string; search_keywords:string[]; marketing_angles:string[]; risks:string[]; status:ProductOpportunityStatus; created_at:string; updated_at:string }
export type BrandGenerationStatus="queued"|"running"|"completed"|"failed";export type BrandDirectionStatus="generated"|"selected"|"rejected"|"approved";
export interface BrandGenerationRun{id:string;organization_id:string;business_id:string;selected_product_id:string;status:BrandGenerationStatus;requested_direction_count:number;provider:"openai"|"mock";model:string;preferences:Record<string,string>;error:string|null;created_at:string;started_at:string|null;completed_at:string|null}
export interface BrandDirection{id:string;organization_id:string;business_id:string;brand_generation_run_id:string;selected_product_id:string;name:string;tagline:string;positioning_statement:string;target_customer:string;customer_pain_points:string[];value_proposition:string;brand_personality:string[];brand_voice:{tone:string;style:string;preferred_language_patterns:string[];avoid_language_patterns:string[]};primary_color:string;secondary_color:string;accent_color:string;typography_direction:string;logo_concept:string;visual_style:string;domain_suggestions:string[];social_handle_suggestions:string[];about_summary:string;store_design_direction:string;status:BrandDirectionStatus;created_at:string;updated_at:string}
export type StoreGenerationStatus="queued"|"running"|"completed"|"failed";export type StoreStatus="draft"|"generated"|"approved"|"published";
export interface StoreGenerationRun{id:string;organization_id:string;business_id:string;approved_brand_id:string;selected_product_id:string;status:StoreGenerationStatus;provider:"openai"|"mock";model:string;preferences:Record<string,string>;error:string|null;created_at:string;started_at:string|null;completed_at:string|null}
export interface Store{id:string;organization_id:string;business_id:string;approved_brand_id:string;selected_product_id:string;generation_run_id:string;name:string;slug:string;status:StoreStatus;theme:Record<string,unknown>;navigation:{label:string;target:string}[];footer:Record<string,unknown>;seo_defaults:Record<string,string>;created_at:string;updated_at:string;approved_at:string|null}
export interface StoreSection{id:string;organization_id:string;business_id:string;store_id:string;section_type:string;position:number;content:Record<string,unknown>;settings:Record<string,unknown>;is_enabled:boolean;created_at:string;updated_at:string}
export interface StorePage{id:string;organization_id:string;business_id:string;store_id:string;page_type:string;slug:string;title:string;seo_title:string;seo_description:string;content:Record<string,unknown>;created_at:string;updated_at:string}
export interface PublicCheckout{store:{name:string;slug:string};product:{name:string;description:string;currency:string;unitPrice:number};shippingAmount:number;taxAmount:number;discountAmount:number}
export interface Order{id:string;organization_id:string;business_id:string;store_id:string;customer_id:string;checkout_session_id:string;order_number:string;status:"pending"|"confirmed"|"cancelled"|"refunded";payment_status:"pending"|"paid"|"failed"|"refunded"|"partially_refunded";fulfillment_status:"unfulfilled"|"processing"|"fulfilled"|"cancelled";currency:string;subtotal_amount:number;shipping_amount:number;tax_amount:number;discount_amount:number;total_amount:number;shipping_address:Record<string,string|null>;billing_address:Record<string,string|null>;customer_email:string;customer_name:string;created_at:string;updated_at:string;paid_at:string|null;cancelled_at:string|null}
export interface OrderItem{id:string;order_id:string;product_name:string;quantity:number;unit_price:number;line_total:number}
export interface PaymentTransaction{id:string;order_id:string|null;checkout_session_id:string;provider:string;provider_transaction_id:string;transaction_type:"payment"|"refund";status:"pending"|"succeeded"|"failed"|"cancelled";currency:string;amount:number;provider_metadata:Record<string,unknown>;created_at:string;updated_at:string}
