"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3,Bot,Boxes,Workflow,Building2,CreditCard,Home,LayoutTemplate,Megaphone,PackageSearch,Palette,Settings,ShoppingBag,Users } from "lucide-react";
import { cn } from "@/lib/utils";
const links=[
 ["Dashboard","/dashboard",Home],["My Businesses","/businesses",Building2],["Product Research","/dashboard/product-research",PackageSearch],["Store Builder","/dashboard/store-builder",LayoutTemplate],["Creative Studio","/dashboard/creative-studio",Palette],["Marketing","/dashboard/marketing",Megaphone],["Orders","/dashboard/orders",ShoppingBag],["Customers","/dashboard/customers",Users],["Analytics","/dashboard/analytics",BarChart3],["AI Manager","/dashboard/ai-manager",Bot],["Integrations","/dashboard/integrations",Boxes],["Billing","/dashboard/billing",CreditCard],["Settings","/dashboard/settings",Settings]
] as const;
export function Sidebar(){const path=usePathname();return <aside className="hidden min-h-screen w-64 shrink-0 border-r border-slate-200 bg-white p-4 lg:block"><Link href="/dashboard" className="mb-7 flex items-center gap-2 px-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-brand-500 text-white"><Workflow size={19}/></span>AI Commerce OS</Link><nav className="space-y-1">{links.map(([label,href,Icon])=><Link key={href} href={href} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50",path===href&&"bg-brand-50 text-brand-600")}><Icon size={18}/>{label}</Link>)}</nav></aside>}
export function TopNavigation({email}:{email?:string}){return <header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 lg:px-8"><div className="font-semibold lg:hidden">AI Commerce OS</div><div className="ml-auto flex items-center gap-3"><span className="hidden text-sm text-muted sm:block">{email}</span><form action="/auth/signout" method="post"><button className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium">Sign out</button></form></div></header>}
export function DashboardShell({email,children}:{email?:string;children:React.ReactNode}){return <div className="flex min-h-screen"><Sidebar/><div className="min-w-0 flex-1"><TopNavigation email={email}/><main className="mx-auto max-w-7xl p-5 lg:p-8">{children}</main></div></div>}
