"use client";
import type { ButtonHTMLAttributes,InputHTMLAttributes,ReactNode,SelectHTMLAttributes } from "react";
import { X,Inbox,LoaderCircle,TriangleAlert } from "lucide-react";
import { cn } from "@/lib/utils";
export function Button({className,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={cn("inline-flex h-10 items-center justify-center rounded-lg bg-brand-500 px-4 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 disabled:cursor-not-allowed disabled:opacity-50",className)} {...props}>{children}</button>}
export function Input({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={cn("h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand-500 focus:ring-4 focus:ring-brand-50",className)} {...props}/>}
export function Dropdown({className,children,...props}:SelectHTMLAttributes<HTMLSelectElement>){return <select className={cn("h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-4 focus:ring-brand-50",className)} {...props}>{children}</select>}
export function Card({className,children}:{className?:string;children:ReactNode}){return <div className={cn("rounded-2xl border border-slate-200 bg-white p-6 shadow-sm",className)}>{children}</div>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"}){const tones={neutral:"bg-slate-100 text-slate-700",success:"bg-emerald-50 text-emerald-700",warning:"bg-amber-50 text-amber-700"};return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize",tones[tone])}>{children}</span>}
export function Modal({open,title,onClose,children}:{open:boolean;title:string;onClose:()=>void;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><Card className="w-full max-w-lg"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><button onClick={onClose} aria-label="Close"><X size={20}/></button></div>{children}</Card></div>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}){return <Card className="grid min-h-64 place-items-center text-center"><div><span className="mx-auto mb-4 grid size-12 place-items-center rounded-xl bg-brand-50 text-brand-500"><Inbox/></span><h2 className="text-lg font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted">{description}</p>{action&&<div className="mt-5">{action}</div>}</div></Card>}
export function LoadingState({label="Loading"}:{label?:string}){return <div className="flex min-h-40 items-center justify-center gap-2 text-sm text-muted"><LoaderCircle className="animate-spin" size={18}/>{label}</div>}
export function ErrorState({message="Something went wrong."}:{message?:string}){return <Card className="flex items-center gap-3 border-red-200 bg-red-50 text-sm text-red-700"><TriangleAlert size={20}/>{message}</Card>}
