import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { BrandPersistence,BrandRefs } from "./execution";
import type { BrandGeneration,BrandGenerationInput } from "./types";
export class SupabaseBrandPersistence implements BrandPersistence{
 constructor(private supabase:SupabaseClient){}
 async start(i:BrandGenerationInput,provider:string,model:string){const{data,error}=await this.supabase.rpc("start_brand_generation",{p_business_id:i.businessId,p_requested_direction_count:i.directionCount,p_provider:provider,p_model:model,p_preferences:i.preferences});if(error)throw new Error(error.code==="23505"?"Brand generation is already running for this business.":`Unable to start brand generation: ${error.message}`);const r=data as{run_id?:string;job_id?:string;selected_product_id?:string}|null;if(!r?.run_id||!r.job_id||!r.selected_product_id)throw new Error("Brand generation did not return valid references");return{runId:r.run_id,jobId:r.job_id,businessId:i.businessId,selectedProductId:r.selected_product_id}}
 async complete(refs:BrandRefs,g:BrandGeneration){const rows=g.directions.map(d=>({name:d.name,tagline:d.tagline,positioning_statement:d.positioningStatement,target_customer:d.targetCustomer,customer_pain_points:d.customerPainPoints,value_proposition:d.valueProposition,brand_personality:d.brandPersonality,brand_voice:{tone:d.brandVoice.tone,style:d.brandVoice.style,preferred_language_patterns:d.brandVoice.preferredLanguagePatterns,avoid_language_patterns:d.brandVoice.avoidLanguagePatterns},primary_color:d.primaryColor,secondary_color:d.secondaryColor,accent_color:d.accentColor,typography_direction:d.typographyDirection,logo_concept:d.logoConcept,visual_style:d.visualStyle,domain_suggestions:d.domainSuggestions,social_handle_suggestions:d.socialHandleSuggestions,about_summary:d.aboutSummary,store_design_direction:d.storeDesignDirection}));const{error}=await this.supabase.rpc("complete_brand_generation",{p_run_id:refs.runId,p_job_id:refs.jobId,p_directions:rows,p_input_tokens:g.usage.inputTokens,p_output_tokens:g.usage.outputTokens,p_total_tokens:g.usage.totalTokens});if(error)throw new Error(`Unable to complete brand generation: ${error.message}`)}
 async fail(refs:BrandRefs,error:string){console.error("Brand generation failed",{...refs,error:error.slice(0,2000)});const{error:e}=await this.supabase.rpc("fail_brand_generation",{p_run_id:refs.runId,p_job_id:refs.jobId,p_error:error.slice(0,2000)});if(e)throw new Error(`Unable to clean up brand generation: ${e.message}`)}
}
