import "server-only";
import { DEFAULT_PRODUCT_RESEARCH_MODEL } from "@/agents/product-research/provider";
import { buildBrandPrompt } from "./prompt";
import type { BrandGenerationInput, BrandProvider } from "./types";
import { brandResponseSchema } from "./validation";

export class OpenAiBrandProvider implements BrandProvider {
  constructor(private apiKey=process.env.OPENAI_API_KEY,private model=process.env.OPENAI_MODEL||DEFAULT_PRODUCT_RESEARCH_MODEL){}
  async generate(input:BrandGenerationInput){
    if(!this.apiKey)throw new Error("OPENAI_API_KEY is not configured");
    const response=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${this.apiKey}`},body:JSON.stringify({model:this.model,temperature:.4,messages:[{role:"system",content:"Create cautious ecommerce brand directions. Return only schema-valid JSON. Never claim trademark, domain, handle, or legal availability."},{role:"user",content:buildBrandPrompt(input)}],response_format:{type:"json_schema",json_schema:{name:"brand_directions",strict:true,schema:responseSchema(input.directionCount)}}})});
    if(!response.ok){const detail=await response.text();console.error("Brand provider failed",{status:response.status,detail:detail.slice(0,500)});throw new Error(`OpenAI request failed with status ${response.status}`)}
    const payload=await response.json() as {choices?:{message?:{content?:string}}[];usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number}};const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("OpenAI returned an empty brand response");let decoded:unknown;try{decoded=JSON.parse(content)}catch{throw new Error("OpenAI returned malformed JSON")}const valid=brandResponseSchema.parse(decoded);if(valid.directions.length>input.directionCount)throw new Error("OpenAI returned too many brand directions");return{directions:valid.directions,provider:"openai" as const,model:this.model,usage:{inputTokens:payload.usage?.prompt_tokens??0,outputTokens:payload.usage?.completion_tokens??0,totalTokens:payload.usage?.total_tokens??0}};
  }
}
function responseSchema(maxItems:number){const strings={type:"array",minItems:1,maxItems:12,items:{type:"string"}};return{type:"object",additionalProperties:false,required:["directions"],properties:{directions:{type:"array",minItems:1,maxItems,items:{type:"object",additionalProperties:false,required:["name","tagline","positioningStatement","targetCustomer","customerPainPoints","valueProposition","brandPersonality","brandVoice","primaryColor","secondaryColor","accentColor","typographyDirection","logoConcept","visualStyle","domainSuggestions","socialHandleSuggestions","aboutSummary","storeDesignDirection"],properties:{name:{type:"string"},tagline:{type:"string"},positioningStatement:{type:"string"},targetCustomer:{type:"string"},customerPainPoints:strings,valueProposition:{type:"string"},brandPersonality:strings,brandVoice:{type:"object",additionalProperties:false,required:["tone","style","preferredLanguagePatterns","avoidLanguagePatterns"],properties:{tone:{type:"string"},style:{type:"string"},preferredLanguagePatterns:strings,avoidLanguagePatterns:strings}},primaryColor:{type:"string",pattern:"^#[0-9A-Fa-f]{6}$"},secondaryColor:{type:"string",pattern:"^#[0-9A-Fa-f]{6}$"},accentColor:{type:"string",pattern:"^#[0-9A-Fa-f]{6}$"},typographyDirection:{type:"string"},logoConcept:{type:"string"},visualStyle:{type:"string"},domainSuggestions:strings,socialHandleSuggestions:strings,aboutSummary:{type:"string"},storeDesignDirection:{type:"string"}}}}}}}
