create type public.customer_address_type as enum('shipping','billing');
create type public.checkout_session_status as enum('created','awaiting_payment','paid','failed','expired','cancelled');
create type public.order_status as enum('pending','confirmed','cancelled','refunded');
create type public.order_payment_status as enum('pending','paid','failed','refunded','partially_refunded');
create type public.fulfillment_status as enum('unfulfilled','processing','fulfilled','cancelled');
create type public.payment_transaction_type as enum('payment','refund');
create type public.payment_transaction_status as enum('pending','succeeded','failed','cancelled');
create sequence public.order_number_seq;

create table public.customers(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,business_id uuid not null,email text not null check(email=lower(email) and char_length(email) between 3 and 320),first_name text not null check(char_length(first_name) between 1 and 80),last_name text not null check(char_length(last_name) between 1 and 80),phone text check(phone is null or char_length(phone) between 7 and 32),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint customers_business_fk foreign key(business_id,organization_id)references public.businesses(id,organization_id)on delete cascade,constraint customers_identity_unique unique(id,business_id,organization_id),unique(business_id,email));
create table public.customer_addresses(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,business_id uuid not null,customer_id uuid not null,address_type public.customer_address_type not null,full_name text not null check(char_length(full_name)between 2 and 161),phone text,address_line_1 text not null check(char_length(address_line_1)between 2 and 200),address_line_2 text,city text not null check(char_length(city)between 1 and 100),region text not null check(char_length(region)between 1 and 100),postal_code text,country_code text not null check(country_code~'^[A-Z]{2}$'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint customer_addresses_customer_fk foreign key(customer_id,business_id,organization_id)references public.customers(id,business_id,organization_id)on delete cascade,constraint customer_addresses_identity_unique unique(id,customer_id,business_id,organization_id));
create table public.checkout_sessions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,business_id uuid not null,store_id uuid not null,customer_id uuid,status public.checkout_session_status not null default'created',currency text not null check(currency~'^[A-Z]{3}$'),subtotal_amount bigint not null check(subtotal_amount>=0),shipping_amount bigint not null default 0 check(shipping_amount>=0),tax_amount bigint not null default 0 check(tax_amount>=0),discount_amount bigint not null default 0 check(discount_amount>=0),total_amount bigint not null check(total_amount>=0 and total_amount=subtotal_amount+shipping_amount+tax_amount-discount_amount),provider text not null,provider_session_id text,payment_token uuid not null default gen_random_uuid(),confirmation_token uuid not null default gen_random_uuid(),expires_at timestamptz not null default(now()+interval'30 minutes'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),completed_at timestamptz,constraint checkout_store_fk foreign key(store_id,business_id,organization_id)references public.stores(id,business_id,organization_id)on delete restrict,constraint checkout_customer_fk foreign key(customer_id,business_id,organization_id)references public.customers(id,business_id,organization_id)on delete restrict,constraint checkout_identity_unique unique(id,business_id,organization_id),unique(payment_token),unique(confirmation_token));
create table public.checkout_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete cascade,business_id uuid not null,checkout_session_id uuid not null,product_opportunity_id uuid not null,product_name text not null,quantity integer not null check(quantity between 1 and 10),unit_price bigint not null check(unit_price>=0),line_total bigint not null check(line_total=unit_price*quantity),created_at timestamptz not null default now(),constraint checkout_items_session_fk foreign key(checkout_session_id,business_id,organization_id)references public.checkout_sessions(id,business_id,organization_id)on delete cascade,constraint checkout_items_product_fk foreign key(product_opportunity_id,business_id,organization_id)references public.product_opportunities(id,business_id,organization_id)on delete restrict,constraint checkout_items_identity_unique unique(id,checkout_session_id,business_id,organization_id));
create table public.orders(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,business_id uuid not null,store_id uuid not null,customer_id uuid not null,checkout_session_id uuid not null unique,order_number text not null unique default('AIC-'||lpad(nextval('public.order_number_seq')::text,6,'0')),status public.order_status not null default'pending',payment_status public.order_payment_status not null default'pending',fulfillment_status public.fulfillment_status not null default'unfulfilled',currency text not null check(currency~'^[A-Z]{3}$'),subtotal_amount bigint not null check(subtotal_amount>=0),shipping_amount bigint not null check(shipping_amount>=0),tax_amount bigint not null check(tax_amount>=0),discount_amount bigint not null check(discount_amount>=0),total_amount bigint not null check(total_amount=subtotal_amount+shipping_amount+tax_amount-discount_amount),shipping_address jsonb not null check(jsonb_typeof(shipping_address)='object'),billing_address jsonb not null check(jsonb_typeof(billing_address)='object'),customer_email text not null,customer_name text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),paid_at timestamptz,cancelled_at timestamptz,constraint orders_store_fk foreign key(store_id,business_id,organization_id)references public.stores(id,business_id,organization_id)on delete restrict,constraint orders_customer_fk foreign key(customer_id,business_id,organization_id)references public.customers(id,business_id,organization_id)on delete restrict,constraint orders_checkout_fk foreign key(checkout_session_id,business_id,organization_id)references public.checkout_sessions(id,business_id,organization_id)on delete restrict,constraint orders_identity_unique unique(id,business_id,organization_id));
create table public.order_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,business_id uuid not null,order_id uuid not null,product_opportunity_id uuid not null,product_name text not null,quantity integer not null check(quantity between 1 and 10),unit_price bigint not null check(unit_price>=0),line_total bigint not null check(line_total=unit_price*quantity),created_at timestamptz not null default now(),constraint order_items_order_fk foreign key(order_id,business_id,organization_id)references public.orders(id,business_id,organization_id)on delete restrict,constraint order_items_product_fk foreign key(product_opportunity_id,business_id,organization_id)references public.product_opportunities(id,business_id,organization_id)on delete restrict);
create table public.payment_transactions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,business_id uuid not null,order_id uuid,checkout_session_id uuid not null,provider text not null,provider_transaction_id text not null,transaction_type public.payment_transaction_type not null,status public.payment_transaction_status not null default'pending',currency text not null check(currency~'^[A-Z]{3}$'),amount bigint not null check(amount>=0),provider_metadata jsonb not null default'{}'::jsonb check(jsonb_typeof(provider_metadata)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint payment_checkout_fk foreign key(checkout_session_id,business_id,organization_id)references public.checkout_sessions(id,business_id,organization_id)on delete restrict,constraint payment_order_fk foreign key(order_id,business_id,organization_id)references public.orders(id,business_id,organization_id)on delete restrict,unique(provider,provider_transaction_id));
create table public.payment_events(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id)on delete restrict,business_id uuid not null,provider text not null,provider_event_id text not null,event_type text not null,payload_hash text not null check(payload_hash~'^[a-f0-9]{64}$'),processed boolean not null default false,processing_error text,created_at timestamptz not null default now(),processed_at timestamptz,constraint payment_events_business_fk foreign key(business_id,organization_id)references public.businesses(id,organization_id)on delete restrict,unique(provider,provider_event_id));

create index customers_business_email_idx on public.customers(business_id,email);create index checkout_status_created_idx on public.checkout_sessions(business_id,status,created_at desc);create index orders_business_created_idx on public.orders(business_id,created_at desc);create index orders_payment_idx on public.orders(business_id,payment_status);create index orders_fulfillment_idx on public.orders(business_id,fulfillment_status);create index payment_transactions_checkout_idx on public.payment_transactions(checkout_session_id);create index payment_events_created_idx on public.payment_events(created_at desc);
alter table public.customers enable row level security;alter table public.customer_addresses enable row level security;alter table public.checkout_sessions enable row level security;alter table public.checkout_items enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.payment_transactions enable row level security;alter table public.payment_events enable row level security;
create policy customers_member_select on public.customers for select to authenticated using(public.is_org_member(organization_id));create policy addresses_member_select on public.customer_addresses for select to authenticated using(public.is_org_member(organization_id));create policy checkouts_member_select on public.checkout_sessions for select to authenticated using(public.is_org_member(organization_id));create policy checkout_items_member_select on public.checkout_items for select to authenticated using(public.is_org_member(organization_id));create policy orders_member_select on public.orders for select to authenticated using(public.is_org_member(organization_id));create policy order_items_member_select on public.order_items for select to authenticated using(public.is_org_member(organization_id));create policy transactions_member_select on public.payment_transactions for select to authenticated using(public.is_org_member(organization_id));create policy events_member_select on public.payment_events for select to authenticated using(public.is_org_member(organization_id));
revoke all on table public.customers,public.customer_addresses,public.checkout_sessions,public.checkout_items,public.orders,public.order_items,public.payment_transactions,public.payment_events from anon,authenticated;grant select on table public.customers,public.customer_addresses,public.checkout_sessions,public.checkout_items,public.orders,public.order_items,public.payment_transactions,public.payment_events to authenticated;

create function public.get_public_checkout(p_slug text)returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('store',jsonb_build_object('name',s.name,'slug',s.slug),'product',jsonb_build_object('name',p.name,'description',p.description,'currency',p.currency,'unitPrice',round(p.suggested_price*100)::bigint),'shippingAmount',0,'taxAmount',0,'discountAmount',0)from public.stores s join public.product_opportunities p on p.id=s.selected_product_id and p.business_id=s.business_id and p.organization_id=s.organization_id and p.status='selected'where s.slug=p_slug and s.status='published'$$;

create function public.create_checkout_session(p_slug text,p_quantity integer,p_first_name text,p_last_name text,p_email text,p_phone text,p_country_code text,p_address_line_1 text,p_address_line_2 text,p_city text,p_region text,p_postal_code text,p_provider text)returns jsonb language plpgsql security definer set search_path='' as $$declare s public.stores%rowtype;p public.product_opportunities%rowtype;c uuid;a uuid;co uuid;unit bigint;subtotal bigint;existing uuid;pay uuid;confirm uuid;begin
 if p_quantity not between 1 and 10 or p_provider<>'mock'then raise exception'Invalid checkout request'using errcode='22023';end if;if p_email<>lower(p_email)or p_email!~'^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'or p_country_code!~'^[A-Z]{2}$'or char_length(trim(p_first_name))not between 1 and 80 or char_length(trim(p_last_name))not between 1 and 80 or char_length(trim(p_address_line_1))not between 2 and 200 or char_length(trim(p_city))not between 1 and 100 or char_length(trim(p_region))not between 1 and 100 then raise exception'Invalid checkout details'using errcode='22023';end if;
 select*into s from public.stores where slug=p_slug and status='published';if s.id is null then raise exception'Published store not found'using errcode='22023';end if;select*into p from public.product_opportunities where id=s.selected_product_id and business_id=s.business_id and organization_id=s.organization_id and status='selected';if p.id is null or p.suggested_price<0 then raise exception'Product unavailable'using errcode='22023';end if;perform pg_advisory_xact_lock(hashtext(s.id::text||lower(p_email))::bigint);select x.id into existing from public.checkout_sessions x where x.store_id=s.id and x.status='awaiting_payment'and x.created_at>now()-interval'10 seconds'and exists(select 1 from public.customers z where z.id=x.customer_id and z.email=lower(p_email))order by x.created_at desc limit 1;if existing is not null then select payment_token,confirmation_token into pay,confirm from public.checkout_sessions where id=existing;return jsonb_build_object('checkoutId',existing,'paymentToken',pay,'confirmationToken',confirm);end if;
 insert into public.customers(organization_id,business_id,email,first_name,last_name,phone)values(s.organization_id,s.business_id,lower(p_email),trim(p_first_name),trim(p_last_name),nullif(trim(p_phone),''))on conflict(business_id,email)do update set first_name=excluded.first_name,last_name=excluded.last_name,phone=excluded.phone,updated_at=now()returning id into c;insert into public.customer_addresses(organization_id,business_id,customer_id,address_type,full_name,phone,address_line_1,address_line_2,city,region,postal_code,country_code)values(s.organization_id,s.business_id,c,'shipping',trim(p_first_name)||' '||trim(p_last_name),nullif(trim(p_phone),''),trim(p_address_line_1),nullif(trim(p_address_line_2),''),trim(p_city),trim(p_region),nullif(trim(p_postal_code),''),p_country_code)returning id into a;
 unit=round(p.suggested_price*100)::bigint;subtotal=unit*p_quantity;insert into public.checkout_sessions(organization_id,business_id,store_id,customer_id,status,currency,subtotal_amount,total_amount,provider)values(s.organization_id,s.business_id,s.id,c,'awaiting_payment',p.currency,subtotal,subtotal,p_provider)returning id,payment_token,confirmation_token into co,pay,confirm;insert into public.checkout_items(organization_id,business_id,checkout_session_id,product_opportunity_id,product_name,quantity,unit_price,line_total)values(s.organization_id,s.business_id,co,p.id,p.name,p_quantity,unit,subtotal);insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,metadata)values(s.organization_id,null,'checkout_created','checkout_session',co,jsonb_build_object('provider',p_provider));return jsonb_build_object('checkoutId',co,'paymentToken',pay,'confirmationToken',confirm,'amount',subtotal,'currency',p.currency);end$$;

create function public.complete_checkout_payment(p_checkout_id uuid,p_payment_token uuid,p_provider text,p_provider_transaction_id text,p_provider_event_id text,p_amount bigint,p_currency text,p_payload_hash text)returns jsonb language plpgsql security definer set search_path='' as $$declare c public.checkout_sessions%rowtype;t uuid;o uuid;addr jsonb;customer public.customers%rowtype;begin
 if p_provider<>'mock'or p_payload_hash!~'^[a-f0-9]{64}$'or p_provider_transaction_id!~'^mock_tx_[a-f0-9-]{36}$'or p_provider_event_id!~'^mock_evt_[a-f0-9-]{36}$'then raise exception'Payment verification failed'using errcode='22023';end if;select*into c from public.checkout_sessions where id=p_checkout_id and payment_token=p_payment_token for update;if c.id is null or c.provider<>p_provider or c.status not in('awaiting_payment','paid')or c.total_amount<>p_amount or c.currency<>p_currency then raise exception'Payment verification failed'using errcode='22023';end if;select id into o from public.orders where checkout_session_id=c.id;if o is not null then return(select public.get_checkout_confirmation(c.confirmation_token));end if;
 insert into public.payment_events(organization_id,business_id,provider,provider_event_id,event_type,payload_hash,processed)values(c.organization_id,c.business_id,p_provider,p_provider_event_id,'payment.succeeded',p_payload_hash,false)on conflict(provider,provider_event_id)do nothing;if not found then raise exception'Webhook replay rejected'using errcode='22023';end if;insert into public.payment_transactions(organization_id,business_id,checkout_session_id,provider,provider_transaction_id,transaction_type,status,currency,amount,provider_metadata)values(c.organization_id,c.business_id,c.id,p_provider,p_provider_transaction_id,'payment','pending',c.currency,c.total_amount,jsonb_build_object('verified',true))returning id into t;
 select*into customer from public.customers where id=c.customer_id and business_id=c.business_id and organization_id=c.organization_id;select jsonb_build_object('fullName',full_name,'phone',phone,'addressLine1',address_line_1,'addressLine2',address_line_2,'city',city,'region',region,'postalCode',postal_code,'countryCode',country_code)into addr from public.customer_addresses where customer_id=customer.id and address_type='shipping'order by created_at desc limit 1;
 insert into public.orders(organization_id,business_id,store_id,customer_id,checkout_session_id,status,payment_status,fulfillment_status,currency,subtotal_amount,shipping_amount,tax_amount,discount_amount,total_amount,shipping_address,billing_address,customer_email,customer_name,paid_at)values(c.organization_id,c.business_id,c.store_id,customer.id,c.id,'confirmed','paid','unfulfilled',c.currency,c.subtotal_amount,c.shipping_amount,c.tax_amount,c.discount_amount,c.total_amount,addr,addr,customer.email,customer.first_name||' '||customer.last_name,now())returning id into o;insert into public.order_items(organization_id,business_id,order_id,product_opportunity_id,product_name,quantity,unit_price,line_total)select organization_id,business_id,o,product_opportunity_id,product_name,quantity,unit_price,line_total from public.checkout_items where checkout_session_id=c.id;update public.payment_transactions set order_id=o,status='succeeded',updated_at=now()where id=t;update public.checkout_sessions set status='paid',completed_at=now(),updated_at=now()where id=c.id;update public.payment_events set processed=true,processed_at=now()where provider=p_provider and provider_event_id=p_provider_event_id;insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id,metadata)values(c.organization_id,null,'payment_succeeded','order',o,jsonb_build_object('provider',p_provider)),(c.organization_id,null,'order_created','order',o,'{}');return(select public.get_checkout_confirmation(c.confirmation_token));end$$;

create function public.fail_checkout_payment(p_checkout_id uuid,p_payment_token uuid,p_provider text,p_provider_transaction_id text,p_status public.payment_transaction_status)returns void language plpgsql security definer set search_path='' as $$declare c public.checkout_sessions%rowtype;begin if p_status not in('failed','cancelled')then raise exception'Invalid failure state'using errcode='22023';end if;select*into c from public.checkout_sessions where id=p_checkout_id and payment_token=p_payment_token and provider=p_provider and status='awaiting_payment'for update;if c.id is null then raise exception'Checkout not found'using errcode='22023';end if;insert into public.payment_transactions(organization_id,business_id,checkout_session_id,provider,provider_transaction_id,transaction_type,status,currency,amount,provider_metadata)values(c.organization_id,c.business_id,c.id,p_provider,p_provider_transaction_id,'payment',p_status,c.currency,c.total_amount,'{"verified":true}')on conflict(provider,provider_transaction_id)do nothing;update public.checkout_sessions set status=case when p_status='cancelled'then'cancelled'::public.checkout_session_status else'failed'::public.checkout_session_status end,updated_at=now()where id=c.id;insert into public.audit_logs(organization_id,user_id,action,entity_type,entity_id)values(c.organization_id,null,case when p_status='cancelled'then'payment_cancelled'else'payment_failed'end,'checkout_session',c.id);end$$;

create function public.get_checkout_confirmation(p_confirmation_token uuid)returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('storeSlug',s.slug,'storeName',s.name,'orderNumber',o.order_number,'customerEmail',o.customer_email,'customerName',o.customer_name,'currency',o.currency,'subtotalAmount',o.subtotal_amount,'shippingAmount',o.shipping_amount,'taxAmount',o.tax_amount,'discountAmount',o.discount_amount,'totalAmount',o.total_amount,'paymentStatus',o.payment_status,'orderStatus',o.status,'fulfillmentStatus',o.fulfillment_status,'provider',c.provider,'items',(select jsonb_agg(jsonb_build_object('productName',i.product_name,'quantity',i.quantity,'unitPrice',i.unit_price,'lineTotal',i.line_total))from public.order_items i where i.order_id=o.id))from public.checkout_sessions c join public.orders o on o.checkout_session_id=c.id join public.stores s on s.id=o.store_id where c.confirmation_token=p_confirmation_token and c.status='paid'$$;

revoke all on function public.get_public_checkout(text),public.create_checkout_session(text,integer,text,text,text,text,text,text,text,text,text,text,text),public.complete_checkout_payment(uuid,uuid,text,text,text,bigint,text,text),public.fail_checkout_payment(uuid,uuid,text,text,public.payment_transaction_status),public.get_checkout_confirmation(uuid)from public,anon,authenticated;
grant execute on function public.get_public_checkout(text),public.create_checkout_session(text,integer,text,text,text,text,text,text,text,text,text,text,text),public.complete_checkout_payment(uuid,uuid,text,text,text,bigint,text,text),public.fail_checkout_payment(uuid,uuid,text,text,public.payment_transaction_status),public.get_checkout_confirmation(uuid)to anon,authenticated;
