begin;
create extension if not exists pgcrypto;
create type public.organization_role as enum ('owner','admin','member');
create type public.business_status as enum ('draft','researching','building','ready','published','paused');
create type public.business_type as enum ('dropshipping');
create type public.ai_job_status as enum ('queued','running','completed','failed','cancelled');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text not null,full_name text,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null check(char_length(name) between 2 and 100),slug text not null unique check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),owner_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organization_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,role public.organization_role not null default 'member',created_at timestamptz not null default now(),unique(organization_id,user_id));
create table public.businesses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,slug text not null,status public.business_status not null default 'draft',business_type public.business_type not null default 'dropshipping',target_country text not null,target_market text not null,starting_budget numeric(14,2) not null check(starting_budget>=0),niche text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,slug));
create table public.ai_jobs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,business_id uuid references public.businesses(id) on delete cascade,job_type text not null,status public.ai_job_status not null default 'queued',input jsonb not null default '{}'::jsonb,output jsonb,error text,attempts integer not null default 0 check(attempts>=0),created_at timestamptz not null default now(),started_at timestamptz,completed_at timestamptz);
create table public.usage_records(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references public.profiles(id),usage_type text not null,quantity numeric not null check(quantity>=0),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid references public.profiles(id),action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index organization_members_user_idx on public.organization_members(user_id,organization_id);
create index businesses_org_idx on public.businesses(organization_id);
create index ai_jobs_org_idx on public.ai_jobs(organization_id,business_id);
create index usage_records_org_idx on public.usage_records(organization_id);
create index audit_logs_org_idx on public.audit_logs(organization_id,created_at desc);

create function public.is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=target_org and user_id=auth.uid())$$;
create function public.is_org_admin(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=target_org and user_id=auth.uid() and role in ('owner','admin'))$$;
revoke all on function public.is_org_member(uuid) from public; grant execute on function public.is_org_member(uuid) to authenticated;
revoke all on function public.is_org_admin(uuid) from public; grant execute on function public.is_org_admin(uuid) to authenticated;

alter table public.profiles enable row level security;alter table public.organizations enable row level security;alter table public.organization_members enable row level security;alter table public.businesses enable row level security;alter table public.ai_jobs enable row level security;alter table public.usage_records enable row level security;alter table public.audit_logs enable row level security;
create policy profiles_select_self on public.profiles for select using(id=auth.uid());create policy profiles_update_self on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy organizations_select_member on public.organizations for select using(public.is_org_member(id));create policy organizations_update_admin on public.organizations for update using(public.is_org_admin(id)) with check(public.is_org_admin(id));
create policy members_select_member on public.organization_members for select using(public.is_org_member(organization_id));create policy members_insert_admin on public.organization_members for insert with check(public.is_org_admin(organization_id));create policy members_update_admin on public.organization_members for update using(public.is_org_admin(organization_id)) with check(public.is_org_admin(organization_id));create policy members_delete_admin on public.organization_members for delete using(public.is_org_admin(organization_id) and role<>'owner');
create policy businesses_member_all on public.businesses for all using(public.is_org_member(organization_id)) with check(public.is_org_member(organization_id));
create policy ai_jobs_member_all on public.ai_jobs for all using(public.is_org_member(organization_id)) with check(public.is_org_member(organization_id) and (business_id is null or exists(select 1 from public.businesses b where b.id=business_id and b.organization_id=organization_id)));
create policy usage_member_select on public.usage_records for select using(public.is_org_member(organization_id));create policy usage_member_insert on public.usage_records for insert with check(public.is_org_member(organization_id) and user_id=auth.uid());
create policy audit_member_select on public.audit_logs for select using(public.is_org_member(organization_id));create policy audit_member_insert on public.audit_logs for insert with check(public.is_org_member(organization_id) and user_id=auth.uid());

create function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger organizations_updated before update on public.organizations for each row execute function public.set_updated_at();create trigger businesses_updated before update on public.businesses for each row execute function public.set_updated_at();
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$declare org_id uuid:=gen_random_uuid();display_name text:=coalesce(nullif(trim(new.raw_user_meta_data->>'full_name'),''),split_part(new.email,'@',1));begin insert into profiles(id,email,full_name) values(new.id,new.email,display_name);insert into organizations(id,name,slug,owner_id) values(org_id,display_name||'''s Workspace','workspace-'||substr(org_id::text,1,8),new.id);insert into organization_members(organization_id,user_id,role) values(org_id,new.id,'owner');return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
commit;
