import{readFileSync}from"node:fs";import{describe,expect,it,vi}from"vitest";import{executeBrandGeneration,type BrandPersistence}from"@/agents/brand/execution";import{MockBrandProvider,MOCK_BRAND_MODEL}from"@/agents/brand/mock-provider";import{OpenAiBrandProvider}from"@/agents/brand/provider";import{getBrandProviderConfig}from"@/agents/brand/provider-factory";import{brandDirectionSchema,brandGenerationRequestSchema,hexColorSchema}from"@/agents/brand/validation";import type{BrandGenerationInput,BrandProvider}from"@/agents/brand/types";
const input:BrandGenerationInput={businessId:"550e8400-e29b-41d4-a716-446655440000",businessName:"Ibeautify",targetCountry:"Uganda",targetMarket:"United States",startingBudget:300,niche:"Pets",selectedProductId:"550e8400-e29b-41d4-a716-446655440001",productName:"Reusable Pet Hair Remover",productCategory:"Pet Cleaning",productDescription:"A reusable remover for furniture.",productTargetCustomer:"Pet owners",suggestedPrice:40,marketingAngles:["before and after"],risks:["competition"],reasoning:"A visual and practical product direction.",directionCount:3,preferences:{}};
const persistence=():BrandPersistence=>({start:vi.fn().mockResolvedValue({runId:"run",jobId:"job",businessId:input.businessId,selectedProductId:input.selectedProductId}),complete:vi.fn(),fail:vi.fn()});
describe("brand creation",()=>{
 it("validates inputs and caps directions",()=>{expect(brandGenerationRequestSchema.safeParse({businessId:input.businessId,directionCount:3}).success).toBe(true);expect(brandGenerationRequestSchema.safeParse({businessId:input.businessId,directionCount:6}).success).toBe(false)});
 it("validates six-digit hex colors",()=>{expect(hexColorSchema.safeParse("#111827").success).toBe(true);expect(hexColorSchema.safeParse("red").success).toBe(false);expect(hexColorSchema.safeParse("#123").success).toBe(false)});
 it("selects providers and rejects invalid configuration",()=>{expect(getBrandProviderConfig({AI_PROVIDER:"mock"}).provider).toBeInstanceOf(MockBrandProvider);expect(getBrandProviderConfig({}).provider).toBeInstanceOf(OpenAiBrandProvider);expect(()=>getBrandProviderConfig({AI_PROVIDER:"other"})).toThrow("AI_PROVIDER must be either openai or mock")});
 it("returns three deterministic, schema-valid pet directions",async()=>{const p=new MockBrandProvider();const a=await p.generate(input);const b=await p.generate(input);expect(a).toEqual(b);expect(a.directions).toHaveLength(3);expect(a.directions.map(x=>x.name)).toEqual(["Pawvia","Kindred Tail","Noma Paw"]);expect(a.directions.every(x=>brandDirectionSchema.safeParse(x).success)).toBe(true);expect(a).toMatchObject({provider:"mock",model:MOCK_BRAND_MODEL,usage:{totalTokens:0}})});
 it("supports other niches deterministically",async()=>{const r=await new MockBrandProvider().generate({...input,niche:"Home",directionCount:2});expect(r.directions).toHaveLength(2);expect(r.directions[0]?.name).toBe("Home Works")});
 it("completes through shared persistence",async()=>{const store=persistence();const result=await executeBrandGeneration(input,"mock",MOCK_BRAND_MODEL,new MockBrandProvider(),store);expect(result.directions).toHaveLength(3);expect(store.complete).toHaveBeenCalledWith(expect.objectContaining({runId:"run"}),expect.objectContaining({provider:"mock",usage:{inputTokens:0,outputTokens:0,totalTokens:0}}));expect(store.fail).not.toHaveBeenCalled()});
 it("cleans up provider and malformed-output failures",async()=>{const store=persistence();const provider:BrandProvider={generate:vi.fn().mockRejectedValue(new Error("malformed output"))};await expect(executeBrandGeneration(input,"openai","model",provider,store)).rejects.toThrow("malformed");expect(store.fail).toHaveBeenCalledWith(expect.objectContaining({runId:"run"}),"malformed output")});
 it("does not contact OpenAI when configuration is missing",async()=>{const fetchSpy=vi.spyOn(globalThis,"fetch");await expect(new OpenAiBrandProvider(undefined,"test").generate(input)).rejects.toThrow("OPENAI_API_KEY");expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore()});
 it("renders mock warnings and Store Creation handoff",()=>{const list=readFileSync("app/businesses/[id]/brand/page.tsx","utf8");const detail=readFileSync("app/businesses/[id]/brand/[directionId]/page.tsx","utf8");const overview=readFileSync("app/businesses/[id]/page.tsx","utf8");expect(list).toContain("Test Data");expect(detail).toContain("not verified market, trademark, domain, or social-handle data");expect(overview).toContain("Approve a brand to unlock");expect(overview).toContain("Generate your structured storefront")});
});
