import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const sql=readFileSync("supabase/migrations/202609110003_brand_creation.sql","utf8");
describe("brand migration security",()=>{
 it("orders after Phase 1B and creates required objects",()=>{expect(sql).toContain("create table public.brand_generation_runs");expect(sql).toContain("create table public.brand_directions")});
 it("enforces cross-tenant composite references",()=>{expect(sql).toContain("brand_runs_product_fk");expect(sql).toContain("brand_directions_run_fk");expect(sql).toContain("product_opportunities_identity_unique")});
 it("enforces active, selected, and approved uniqueness",()=>{expect(sql).toContain("brand_runs_one_active_per_business");expect(sql).toContain("brand_directions_one_selected_per_business");expect(sql).toContain("brand_directions_one_approved_per_business")});
 it("has read-only member RLS without broad mutations",()=>{expect(sql).toContain("brand_runs_member_select");expect(sql).toContain("brand_directions_member_select");expect(sql).not.toMatch(/create policy brand_[\s\S]{0,120}for (insert|update|delete|all)/i)});
 it("uses narrow authenticated RPC grants and safe paths",()=>{for(const fn of["start_brand_generation","complete_brand_generation","fail_brand_generation","select_brand_direction","reject_brand_direction","update_selected_brand","approve_brand_direction"]){expect(sql).toContain(`public.${fn}`)}expect((sql.match(/security definer set search_path=''/g)||[]).length).toBe(7);expect(sql).toContain("from public,anon");expect(sql).toContain("to authenticated")});
 it("checks authentication, membership, selected product, and completed research",()=>{expect(sql).toContain("auth.uid()");expect(sql).toContain("public.organization_members");expect(sql).toContain("p.status='selected'");expect(sql).toContain("r.status='completed'")});
 it("preserves failures and audit actions",()=>{expect(sql).toContain("status='failed'");for(const action of["brand_direction_selected","brand_direction_rejected","brand_direction_updated","brand_approved"])expect(sql).toContain(`'${action}'`)});
 it("cascades business/run deletion and restricts selected-product deletion",()=>{expect(sql).toContain("references public.businesses(id,organization_id) on delete cascade");expect(sql).toContain("references public.product_opportunities(id,business_id,organization_id) on delete restrict");expect(sql).toContain("references public.brand_generation_runs(id,selected_product_id,business_id,organization_id) on delete cascade")});
});
