import { describe,expect,it,vi } from "vitest";
import { executeProductResearch,type ProductResearchPersistence } from "@/agents/product-research/execution";
import type { ProductResearchInput,ProductResearchProvider } from "@/agents/product-research/types";
import { createResearchUsageRecord } from "@/agents/product-research/usage";

const input:ProductResearchInput={businessId:"550e8400-e29b-41d4-a716-446655440000",targetCountry:"Kenya",targetMarket:"East Africa",niche:"Pets",budget:1000,maximumSupplierCost:30,preferredSellingPrice:80,productCount:1};
const product={name:"Portable pet bottle",category:"Pets",description:"A portable hydration bottle for pet owners.",targetCustomer:"Active dog owners",supplierCost:12,suggestedPrice:40,currency:"USD",demandScore:70,competitionScore:35,trendScore:65,marketingScore:80,shippingScore:90,riskScore:20,reasoning:"Compact, visual, and suitable for impulse-driven demonstrations.",searchKeywords:["dog water bottle"],marketingAngles:["hydrate anywhere"],risks:["commodity competition"]};
function persistence():ProductResearchPersistence{return {start:vi.fn().mockResolvedValue({runId:"run",jobId:"job",businessId:input.businessId}),complete:vi.fn().mockResolvedValue(undefined),fail:vi.fn().mockResolvedValue(undefined)}};
describe("product research execution",()=>{
  it("scores results and passes usage to persistence",async()=>{const store=persistence();const provider:ProductResearchProvider={generate:vi.fn().mockResolvedValue({products:[product],model:"test-model",usage:{inputTokens:10,outputTokens:20,totalTokens:30}})};const result=await executeProductResearch(input,provider,store);expect(result.products[0]?.overallScore).toBeGreaterThan(0);expect(store.complete).toHaveBeenCalledWith(expect.anything(),expect.anything(),expect.objectContaining({usage:{inputTokens:10,outputTokens:20,totalTokens:30}}));expect(store.fail).not.toHaveBeenCalled()});
  it("cleans up failed provider work",async()=>{const store=persistence();const provider:ProductResearchProvider={generate:vi.fn().mockRejectedValue(new Error("provider unavailable"))};await expect(executeProductResearch(input,provider,store)).rejects.toThrow("provider unavailable");expect(store.fail).toHaveBeenCalledWith(expect.objectContaining({runId:"run",jobId:"job"}),"provider unavailable")});
  it("surfaces duplicate active research before provider usage",async()=>{const store=persistence();vi.mocked(store.start).mockRejectedValue(new Error("Research is already running for this business."));const provider:ProductResearchProvider={generate:vi.fn()};await expect(executeProductResearch(input,provider,store)).rejects.toThrow("already running");expect(provider.generate).not.toHaveBeenCalled()});
  it("builds a complete tenant-scoped usage record",()=>{expect(createResearchUsageRecord({organizationId:"org",userId:"user",runId:"run"},{products:[product],model:"test-model",usage:{inputTokens:10,outputTokens:20,totalTokens:30}})).toEqual({organization_id:"org",user_id:"user",usage_type:"product_research",quantity:30,metadata:{model:"test-model",input_tokens:10,output_tokens:20,total_tokens:30,research_run_id:"run"}})});
});
